### ISSUE TITLE
KGS Bots version 1.0

### ISSUE THREAD

**Issue by Spoekenkieker** [waltheri/go-libraries#17]
**KGS Bots version 1.0,** Open Source program to run bots on KGS – https://github.com/kgsnick/KGSBots-version-1.0

For English language info see L19 thread [KGS Bots version 1.0](http://www.lifein19x19.com/forum/viewtopic.php?p=206862#p206862)

**Comment by waltheri** [comment]
English documentation is missing, so it isn't very usable for foreign programmers.
