### ISSUE TITLE
Adding general go content?

### ISSUE THREAD

**Issue by yewang** [waltheri/go-libraries#28]
What are your thoughts about expanding the scope of this list to contain links to general go content (like problems, commented games, books, articles, etc.) that are available under "open" licenses (like creative commons, public domain, etc.)?

**Comment by yewang** [comment]
Some examples for content that could be linked to in a "Go Content (books, SGFs, articles, etc.)" section:

- [GoGameGuru Commented Games](https://github.com/gogameguru/commented-go-games)
- [GoGameGuru Go Problems](https://github.com/gogameguru/go-problems)
- [Shape Up! by Charles Matthews and Seong-June Kim](https://forums.online-go.com/t/ogs-is-proud-to-host-shape-up/3478)
- [81 Little Lions by Immanuel  deVillers](https://forums.online-go.com/t/81-little-lions-an-introduction-to-the-9x9-board-for-advanced-beginners/3138)

All of these have been released under Creative Commons licenses. Other possibilities include very old (and hence public domain) go problem collections.

**Comment by apetresc** [comment]
But why? There are so many more appropriate places for such a list than a GitHub README...

**Comment by yewang** [comment]
I wound up creating a wiki post on the OGS forums to catalog some Creative Commons Go materials.

See: https://forums.online-go.com/t/go-books-content-in-the-creative-commons/24517
